### ISSUE TITLE
Use Tinty

### ISSUE THREAD

**Issue by jpsalo** [jpsalo/dotfiles#46]
https://github.com/tinted-theming/tinty

**TODO**
- **Update installer**:
- [x] Tinty: install; symlink config; run init commands etc.
- [x] tmux: `brew install tpm` and linux variant
- [x] ghostty: install; `mkdir -p ~/.config/ghostty/themes`
- [ ] Refactor theme.sh: Use only for things not done with tinty
